# Configuration for probot-auto-merge - https://github.com/bobvanderlinden/probot-auto-merge

updateBranch: true
deleteBranchAfterMerge: true
reportStatus: true
mergeMethod: merge

minApprovals:
  COLLABORATOR: 0
maxRequestedChanges:
  NONE: 0
blockingLabels:
- blocked

# Will merge whenever the above conditions are met, but also
# the owner has approved or merge label was added.
rules:
- minApprovals:
    OWNER: 0

mergeCommitMessage: "{title} (#{number})"